

services:
  postgres:
    image: postgres:latest
    container_name: postgres-rag-app
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ragapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
